import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import React from 'react';
import TopMenu from '@components/TopMenu';
import SideMenu from '@components/SideMenu';
import Footer from "@components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
         <div className="flex flex-col h-screen">
          <TopMenu />
          <div className="flex flex-1 pr-6 bg-gray-800">
            <SideMenu />
            <main className="rounded-2xl flex-1 p-4 bg-white">
              {children}
            </main> 
          </div>
          <Footer />
        </div>
        </body>
    </html>
  );
}
